// pm0 daemon control-plane protocol.
//
// Transport: gRPC over a Unix domain socket at ~/.pm0/pm0.sock (0600).
// This schema is the contract between the CLI, the Go SDK (pkg/client) and
// the daemon. It is deliberately PM2-shaped where PM2
// scripts depend on field names: see docs/compat.md for the JSON contract
// (jlist keys, status vocabulary, defaults). Any field added here must keep
// numbers assigned once and never reused (buf breaking checks enforce this).
//
// Version: v1. M0 pin. Extensions (metrics stream, monit feed, watch events,
// health checks, cluster) land as additional RPCs/messages in later
// milestones without breaking this file.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: daemon.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Daemon_Ping_FullMethodName            = "/pm0.v1.Daemon/Ping"
	Daemon_StartProcess_FullMethodName    = "/pm0.v1.Daemon/StartProcess"
	Daemon_StopProcess_FullMethodName     = "/pm0.v1.Daemon/StopProcess"
	Daemon_RestartProcess_FullMethodName  = "/pm0.v1.Daemon/RestartProcess"
	Daemon_DeleteProcess_FullMethodName   = "/pm0.v1.Daemon/DeleteProcess"
	Daemon_ReloadProcess_FullMethodName   = "/pm0.v1.Daemon/ReloadProcess"
	Daemon_ScaleProcess_FullMethodName    = "/pm0.v1.Daemon/ScaleProcess"
	Daemon_ListProcesses_FullMethodName   = "/pm0.v1.Daemon/ListProcesses"
	Daemon_DescribeProcess_FullMethodName = "/pm0.v1.Daemon/DescribeProcess"
	Daemon_StreamLogs_FullMethodName      = "/pm0.v1.Daemon/StreamLogs"
	Daemon_Save_FullMethodName            = "/pm0.v1.Daemon/Save"
	Daemon_Resurrect_FullMethodName       = "/pm0.v1.Daemon/Resurrect"
	Daemon_UpdateDaemon_FullMethodName    = "/pm0.v1.Daemon/UpdateDaemon"
	Daemon_KillDaemon_FullMethodName      = "/pm0.v1.Daemon/KillDaemon"
)

// DaemonClient is the client API for Daemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Daemon is the control-plane service the daemon exposes on its UDS.
type DaemonClient interface {
	// Liveness + daemon metadata. Also the CLI's retry probe while the daemon
	// is mid-update (in-place re-exec) — callers may receive an "updating"
	// error until the new process has re-adopted apps.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Start one or more apps from a spec (fork mode in v1; N instances are
	// named app-0..N-1 and do NOT share a port — see docs/compat.md).
	StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessResponse, error)
	// Stop: graceful kill_signal, then force after kill_timeout. State stays
	// registered (status stopped) until DeleteProcess.
	StopProcess(ctx context.Context, in *StopProcessRequest, opts ...grpc.CallOption) (*StopProcessResponse, error)
	// Restart = stop (if running) + start, preserving pm_id and config.
	RestartProcess(ctx context.Context, in *RestartProcessRequest, opts ...grpc.CallOption) (*RestartProcessResponse, error)
	// Delete = stop (if running) + forget. pm_id may be reused afterwards.
	DeleteProcess(ctx context.Context, in *DeleteProcessRequest, opts ...grpc.CallOption) (*DeleteProcessResponse, error)
	// Reload: rolling restart, one instance at a time, health-gated (M5+).
	// Pre-cluster this still yields semi-zero-downtime for N-instance apps.
	ReloadProcess(ctx context.Context, in *ReloadProcessRequest, opts ...grpc.CallOption) (*ReloadProcessResponse, error)
	// Scale: adjust instance count of an app by +/-N (fork mode).
	ScaleProcess(ctx context.Context, in *ScaleProcessRequest, opts ...grpc.CallOption) (*ScaleProcessResponse, error)
	// List all apps (backing for `pm0 list` and `pm0 jlist`).
	ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error)
	// Describe one app in full (backing for `pm0 describe` / `pm0 show`).
	DescribeProcess(ctx context.Context, in *DescribeProcessRequest, opts ...grpc.CallOption) (*DescribeProcessResponse, error)
	// StreamLogs tails app output. First response carries the backlog
	// (ring buffer), then live lines follow. Server sends backlog only when
	// include_backlog is set. Lines may carry drop markers
	// ("[pm0: N lines dropped]") — never silent drops (invariant I8).
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	// Save current app set to dump.json (atomic write, invariant I4).
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	// Resurrect: adopt apps from dump.json at daemon start.
	Resurrect(ctx context.Context, in *ResurrectRequest, opts ...grpc.CallOption) (*ResurrectResponse, error)
	// UpdateDaemon: in-place re-exec (syscall.Exec, same PID). Children
	// survive; the new process re-reads dump.json and re-adopts. The stream
	// reports "re-execing" just before the exec; the CLI then polls Ping.
	UpdateDaemon(ctx context.Context, in *UpdateDaemonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateDaemonEvent], error)
	// KillDaemon: stop all apps, unlink socket, exit. Children are stopped
	// first (invariant I1); `kill --force` skips stopping.
	KillDaemon(ctx context.Context, in *KillDaemonRequest, opts ...grpc.CallOption) (*KillDaemonResponse, error)
}

type daemonClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonClient(cc grpc.ClientConnInterface) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Daemon_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartProcessResponse)
	err := c.cc.Invoke(ctx, Daemon_StartProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) StopProcess(ctx context.Context, in *StopProcessRequest, opts ...grpc.CallOption) (*StopProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopProcessResponse)
	err := c.cc.Invoke(ctx, Daemon_StopProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) RestartProcess(ctx context.Context, in *RestartProcessRequest, opts ...grpc.CallOption) (*RestartProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartProcessResponse)
	err := c.cc.Invoke(ctx, Daemon_RestartProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) DeleteProcess(ctx context.Context, in *DeleteProcessRequest, opts ...grpc.CallOption) (*DeleteProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProcessResponse)
	err := c.cc.Invoke(ctx, Daemon_DeleteProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ReloadProcess(ctx context.Context, in *ReloadProcessRequest, opts ...grpc.CallOption) (*ReloadProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadProcessResponse)
	err := c.cc.Invoke(ctx, Daemon_ReloadProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ScaleProcess(ctx context.Context, in *ScaleProcessRequest, opts ...grpc.CallOption) (*ScaleProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaleProcessResponse)
	err := c.cc.Invoke(ctx, Daemon_ScaleProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcessesResponse)
	err := c.cc.Invoke(ctx, Daemon_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) DescribeProcess(ctx context.Context, in *DescribeProcessRequest, opts ...grpc.CallOption) (*DescribeProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeProcessResponse)
	err := c.cc.Invoke(ctx, Daemon_DescribeProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Daemon_ServiceDesc.Streams[0], Daemon_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Daemon_StreamLogsClient = grpc.ServerStreamingClient[LogLine]

func (c *daemonClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, Daemon_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) Resurrect(ctx context.Context, in *ResurrectRequest, opts ...grpc.CallOption) (*ResurrectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResurrectResponse)
	err := c.cc.Invoke(ctx, Daemon_Resurrect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) UpdateDaemon(ctx context.Context, in *UpdateDaemonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateDaemonEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Daemon_ServiceDesc.Streams[1], Daemon_UpdateDaemon_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateDaemonRequest, UpdateDaemonEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Daemon_UpdateDaemonClient = grpc.ServerStreamingClient[UpdateDaemonEvent]

func (c *daemonClient) KillDaemon(ctx context.Context, in *KillDaemonRequest, opts ...grpc.CallOption) (*KillDaemonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillDaemonResponse)
	err := c.cc.Invoke(ctx, Daemon_KillDaemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServer is the server API for Daemon service.
// All implementations must embed UnimplementedDaemonServer
// for forward compatibility.
//
// Daemon is the control-plane service the daemon exposes on its UDS.
type DaemonServer interface {
	// Liveness + daemon metadata. Also the CLI's retry probe while the daemon
	// is mid-update (in-place re-exec) — callers may receive an "updating"
	// error until the new process has re-adopted apps.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Start one or more apps from a spec (fork mode in v1; N instances are
	// named app-0..N-1 and do NOT share a port — see docs/compat.md).
	StartProcess(context.Context, *StartProcessRequest) (*StartProcessResponse, error)
	// Stop: graceful kill_signal, then force after kill_timeout. State stays
	// registered (status stopped) until DeleteProcess.
	StopProcess(context.Context, *StopProcessRequest) (*StopProcessResponse, error)
	// Restart = stop (if running) + start, preserving pm_id and config.
	RestartProcess(context.Context, *RestartProcessRequest) (*RestartProcessResponse, error)
	// Delete = stop (if running) + forget. pm_id may be reused afterwards.
	DeleteProcess(context.Context, *DeleteProcessRequest) (*DeleteProcessResponse, error)
	// Reload: rolling restart, one instance at a time, health-gated (M5+).
	// Pre-cluster this still yields semi-zero-downtime for N-instance apps.
	ReloadProcess(context.Context, *ReloadProcessRequest) (*ReloadProcessResponse, error)
	// Scale: adjust instance count of an app by +/-N (fork mode).
	ScaleProcess(context.Context, *ScaleProcessRequest) (*ScaleProcessResponse, error)
	// List all apps (backing for `pm0 list` and `pm0 jlist`).
	ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error)
	// Describe one app in full (backing for `pm0 describe` / `pm0 show`).
	DescribeProcess(context.Context, *DescribeProcessRequest) (*DescribeProcessResponse, error)
	// StreamLogs tails app output. First response carries the backlog
	// (ring buffer), then live lines follow. Server sends backlog only when
	// include_backlog is set. Lines may carry drop markers
	// ("[pm0: N lines dropped]") — never silent drops (invariant I8).
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogLine]) error
	// Save current app set to dump.json (atomic write, invariant I4).
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
	// Resurrect: adopt apps from dump.json at daemon start.
	Resurrect(context.Context, *ResurrectRequest) (*ResurrectResponse, error)
	// UpdateDaemon: in-place re-exec (syscall.Exec, same PID). Children
	// survive; the new process re-reads dump.json and re-adopts. The stream
	// reports "re-execing" just before the exec; the CLI then polls Ping.
	UpdateDaemon(*UpdateDaemonRequest, grpc.ServerStreamingServer[UpdateDaemonEvent]) error
	// KillDaemon: stop all apps, unlink socket, exit. Children are stopped
	// first (invariant I1); `kill --force` skips stopping.
	KillDaemon(context.Context, *KillDaemonRequest) (*KillDaemonResponse, error)
	mustEmbedUnimplementedDaemonServer()
}

// UnimplementedDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServer struct{}

func (UnimplementedDaemonServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDaemonServer) StartProcess(context.Context, *StartProcessRequest) (*StartProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartProcess not implemented")
}
func (UnimplementedDaemonServer) StopProcess(context.Context, *StopProcessRequest) (*StopProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopProcess not implemented")
}
func (UnimplementedDaemonServer) RestartProcess(context.Context, *RestartProcessRequest) (*RestartProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartProcess not implemented")
}
func (UnimplementedDaemonServer) DeleteProcess(context.Context, *DeleteProcessRequest) (*DeleteProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProcess not implemented")
}
func (UnimplementedDaemonServer) ReloadProcess(context.Context, *ReloadProcessRequest) (*ReloadProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadProcess not implemented")
}
func (UnimplementedDaemonServer) ScaleProcess(context.Context, *ScaleProcessRequest) (*ScaleProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScaleProcess not implemented")
}
func (UnimplementedDaemonServer) ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedDaemonServer) DescribeProcess(context.Context, *DescribeProcessRequest) (*DescribeProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeProcess not implemented")
}
func (UnimplementedDaemonServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedDaemonServer) Save(context.Context, *SaveRequest) (*SaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedDaemonServer) Resurrect(context.Context, *ResurrectRequest) (*ResurrectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resurrect not implemented")
}
func (UnimplementedDaemonServer) UpdateDaemon(*UpdateDaemonRequest, grpc.ServerStreamingServer[UpdateDaemonEvent]) error {
	return status.Error(codes.Unimplemented, "method UpdateDaemon not implemented")
}
func (UnimplementedDaemonServer) KillDaemon(context.Context, *KillDaemonRequest) (*KillDaemonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillDaemon not implemented")
}
func (UnimplementedDaemonServer) mustEmbedUnimplementedDaemonServer() {}
func (UnimplementedDaemonServer) testEmbeddedByValue()                {}

// UnsafeDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServer will
// result in compilation errors.
type UnsafeDaemonServer interface {
	mustEmbedUnimplementedDaemonServer()
}

func RegisterDaemonServer(s grpc.ServiceRegistrar, srv DaemonServer) {
	// If the following call panics, it indicates UnimplementedDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Daemon_ServiceDesc, srv)
}

func _Daemon_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_StartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).StartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_StartProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).StartProcess(ctx, req.(*StartProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_StopProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).StopProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_StopProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).StopProcess(ctx, req.(*StopProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_RestartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).RestartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_RestartProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).RestartProcess(ctx, req.(*RestartProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_DeleteProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).DeleteProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_DeleteProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).DeleteProcess(ctx, req.(*DeleteProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ReloadProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ReloadProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ReloadProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ReloadProcess(ctx, req.(*ReloadProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ScaleProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ScaleProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ScaleProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ScaleProcess(ctx, req.(*ScaleProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListProcesses(ctx, req.(*ListProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_DescribeProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).DescribeProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_DescribeProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).DescribeProcess(ctx, req.(*DescribeProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Daemon_StreamLogsServer = grpc.ServerStreamingServer[LogLine]

func _Daemon_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_Resurrect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResurrectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).Resurrect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_Resurrect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).Resurrect(ctx, req.(*ResurrectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_UpdateDaemon_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdateDaemonRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).UpdateDaemon(m, &grpc.GenericServerStream[UpdateDaemonRequest, UpdateDaemonEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Daemon_UpdateDaemonServer = grpc.ServerStreamingServer[UpdateDaemonEvent]

func _Daemon_KillDaemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillDaemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).KillDaemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_KillDaemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).KillDaemon(ctx, req.(*KillDaemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Daemon_ServiceDesc is the grpc.ServiceDesc for Daemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Daemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pm0.v1.Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Daemon_Ping_Handler,
		},
		{
			MethodName: "StartProcess",
			Handler:    _Daemon_StartProcess_Handler,
		},
		{
			MethodName: "StopProcess",
			Handler:    _Daemon_StopProcess_Handler,
		},
		{
			MethodName: "RestartProcess",
			Handler:    _Daemon_RestartProcess_Handler,
		},
		{
			MethodName: "DeleteProcess",
			Handler:    _Daemon_DeleteProcess_Handler,
		},
		{
			MethodName: "ReloadProcess",
			Handler:    _Daemon_ReloadProcess_Handler,
		},
		{
			MethodName: "ScaleProcess",
			Handler:    _Daemon_ScaleProcess_Handler,
		},
		{
			MethodName: "ListProcesses",
			Handler:    _Daemon_ListProcesses_Handler,
		},
		{
			MethodName: "DescribeProcess",
			Handler:    _Daemon_DescribeProcess_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _Daemon_Save_Handler,
		},
		{
			MethodName: "Resurrect",
			Handler:    _Daemon_Resurrect_Handler,
		},
		{
			MethodName: "KillDaemon",
			Handler:    _Daemon_KillDaemon_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _Daemon_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateDaemon",
			Handler:       _Daemon_UpdateDaemon_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemon.proto",
}
