// pm0 daemon control-plane protocol.
//
// Transport: gRPC over a Unix domain socket at ~/.pm0/pm0.sock (0600).
// This schema is the contract between the CLI, the Go SDK (pkg/client) and
// the daemon. It is deliberately PM2-shaped where PM2
// scripts depend on field names: see docs/compat.md for the JSON contract
// (jlist keys, status vocabulary, defaults). Any field added here must keep
// numbers assigned once and never reused (buf breaking checks enforce this).
//
// Version: v1. M0 pin. Extensions (metrics stream, monit feed, watch events,
// health checks, cluster) land as additional RPCs/messages in later
// milestones without breaking this file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: daemon.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessStatus mirrors PM2's status vocabulary exactly — these strings are
// load-bearing for scripts that parse jlist (docs/compat.md).
type ProcessStatus int32

const (
	ProcessStatus_PROCESS_STATUS_UNSPECIFIED ProcessStatus = 0
	ProcessStatus_PROCESS_STATUS_LAUNCHING   ProcessStatus = 1 // "launching"
	ProcessStatus_PROCESS_STATUS_ONLINE      ProcessStatus = 2 // "online"
	ProcessStatus_PROCESS_STATUS_STOPPED     ProcessStatus = 3 // "stopped" (intentional stop or never started)
	ProcessStatus_PROCESS_STATUS_STOPPING    ProcessStatus = 4 // "stopping"
	ProcessStatus_PROCESS_STATUS_WAITING     ProcessStatus = 5 // "waiting restart" (inside restart_delay / backoff) — observed pm2 string
	ProcessStatus_PROCESS_STATUS_ERRORED     ProcessStatus = 6 // "errored" (crash-loop exhausted max_restarts)
)

// Enum value maps for ProcessStatus.
var (
	ProcessStatus_name = map[int32]string{
		0: "PROCESS_STATUS_UNSPECIFIED",
		1: "PROCESS_STATUS_LAUNCHING",
		2: "PROCESS_STATUS_ONLINE",
		3: "PROCESS_STATUS_STOPPED",
		4: "PROCESS_STATUS_STOPPING",
		5: "PROCESS_STATUS_WAITING",
		6: "PROCESS_STATUS_ERRORED",
	}
	ProcessStatus_value = map[string]int32{
		"PROCESS_STATUS_UNSPECIFIED": 0,
		"PROCESS_STATUS_LAUNCHING":   1,
		"PROCESS_STATUS_ONLINE":      2,
		"PROCESS_STATUS_STOPPED":     3,
		"PROCESS_STATUS_STOPPING":    4,
		"PROCESS_STATUS_WAITING":     5,
		"PROCESS_STATUS_ERRORED":     6,
	}
)

func (x ProcessStatus) Enum() *ProcessStatus {
	p := new(ProcessStatus)
	*p = x
	return p
}

func (x ProcessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_enumTypes[0].Descriptor()
}

func (ProcessStatus) Type() protoreflect.EnumType {
	return &file_daemon_proto_enumTypes[0]
}

func (x ProcessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessStatus.Descriptor instead.
func (ProcessStatus) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

type LogLine_Stream int32

const (
	LogLine_STREAM_UNSPECIFIED LogLine_Stream = 0
	LogLine_STREAM_STDOUT      LogLine_Stream = 1
	LogLine_STREAM_STDERR      LogLine_Stream = 2
)

// Enum value maps for LogLine_Stream.
var (
	LogLine_Stream_name = map[int32]string{
		0: "STREAM_UNSPECIFIED",
		1: "STREAM_STDOUT",
		2: "STREAM_STDERR",
	}
	LogLine_Stream_value = map[string]int32{
		"STREAM_UNSPECIFIED": 0,
		"STREAM_STDOUT":      1,
		"STREAM_STDERR":      2,
	}
)

func (x LogLine_Stream) Enum() *LogLine_Stream {
	p := new(LogLine_Stream)
	*p = x
	return p
}

func (x LogLine_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLine_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_enumTypes[1].Descriptor()
}

func (LogLine_Stream) Type() protoreflect.EnumType {
	return &file_daemon_proto_enumTypes[1]
}

func (x LogLine_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLine_Stream.Descriptor instead.
func (LogLine_Stream) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{21, 0}
}

// Selector targets one or more apps. CLI grammar:
//
//	<name> | <name1> <name2> | <pm_id> | all
//
// If multiple fields are set, they are OR-ed; empty selector with
// require_explicit=false means all.
type Selector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	PmIds         []int32                `protobuf:"varint,2,rep,packed,name=pm_ids,json=pmIds,proto3" json:"pm_ids,omitempty"`
	All           bool                   `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selector) Reset() {
	*x = Selector{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *Selector) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *Selector) GetPmIds() []int32 {
	if x != nil {
		return x.PmIds
	}
	return nil
}

func (x *Selector) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

type PingResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit  string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	Pid     int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	// Effective kill-path mode: "cgroup-kill" | "cgroup-freeze" | "pgid".
	KillMode      string `protobuf:"bytes,4,opt,name=kill_mode,json=killMode,proto3" json:"kill_mode,omitempty"`
	KernelRelease string `protobuf:"bytes,5,opt,name=kernel_release,json=kernelRelease,proto3" json:"kernel_release,omitempty"`
	// Non-empty when cgroup accounting/enforcement is degraded (e.g. "memory
	// controller not delegated; accounting only"). Mirrors what doctor prints.
	CgroupWarning string `protobuf:"bytes,6,opt,name=cgroup_warning,json=cgroupWarning,proto3" json:"cgroup_warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *PingResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PingResponse) GetKillMode() string {
	if x != nil {
		return x.KillMode
	}
	return ""
}

func (x *PingResponse) GetKernelRelease() string {
	if x != nil {
		return x.KernelRelease
	}
	return ""
}

func (x *PingResponse) GetCgroupWarning() string {
	if x != nil {
		return x.CgroupWarning
	}
	return ""
}

type ProcessSpec struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Script string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"` // path to script/binary (pm_exec_path)
	Args   []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// "" = auto-detect (shebang/extension), "none" = exec script directly,
	// otherwise interpreter binary path (node, python, ...).
	Interpreter           string            `protobuf:"bytes,4,opt,name=interpreter,proto3" json:"interpreter,omitempty"`
	InterpreterArgs       []string          `protobuf:"bytes,5,rep,name=interpreter_args,json=interpreterArgs,proto3" json:"interpreter_args,omitempty"`
	Cwd                   string            `protobuf:"bytes,6,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env                   map[string]string `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Instances             int32             `protobuf:"varint,8,opt,name=instances,proto3" json:"instances,omitempty"`              // 1 = single fork; N = app-0..N-1 (no shared port)
	ExecMode              string            `protobuf:"bytes,9,opt,name=exec_mode,json=execMode,proto3" json:"exec_mode,omitempty"` // "fork" (only mode in v1) | "cluster" (M6)
	Autorestart           bool              `protobuf:"varint,10,opt,name=autorestart,proto3" json:"autorestart,omitempty"`
	KillSignal            string            `protobuf:"bytes,11,opt,name=kill_signal,json=killSignal,proto3" json:"kill_signal,omitempty"`                                       // default "SIGINT" (PM2 compat)
	KillTimeoutMs         int32             `protobuf:"varint,12,opt,name=kill_timeout_ms,json=killTimeoutMs,proto3" json:"kill_timeout_ms,omitempty"`                           // default 1600 (PM2 compat)
	MaxRestarts           int32             `protobuf:"varint,13,opt,name=max_restarts,json=maxRestarts,proto3" json:"max_restarts,omitempty"`                                   // default 16 (PM2 compat)
	MinUptimeMs           int64             `protobuf:"varint,14,opt,name=min_uptime_ms,json=minUptimeMs,proto3" json:"min_uptime_ms,omitempty"`                                 // default 1000 (PM2 compat)
	MaxMemoryRestartBytes int64             `protobuf:"varint,15,opt,name=max_memory_restart_bytes,json=maxMemoryRestartBytes,proto3" json:"max_memory_restart_bytes,omitempty"` // 0 = disabled
	CronRestart           string            `protobuf:"bytes,16,opt,name=cron_restart,json=cronRestart,proto3" json:"cron_restart,omitempty"`                                    // cron expression, empty = none
	Watch                 bool              `protobuf:"varint,17,opt,name=watch,proto3" json:"watch,omitempty"`
	// M2 schema correction: pm2's actual option is exp_backoff_restart_delay
	// (a number of ms, source: pm2 lib/API/schema.json), not a boolean flag.
	// 0 = off; when set, first backoff sleep = this value, later sleeps grow
	// x1.5 capped at 15000ms (observed pm2 God.handleExit).
	ExpBackoffRestartDelayMs int64 `protobuf:"varint,18,opt,name=exp_backoff_restart_delay_ms,json=expBackoffRestartDelayMs,proto3" json:"exp_backoff_restart_delay_ms,omitempty"` // opt-in exponential backoff (0 = off)
	WaitReady                bool  `protobuf:"varint,19,opt,name=wait_ready,json=waitReady,proto3" json:"wait_ready,omitempty"`                                                    // sd_notify / ready-line gating (M5)
	ListenTimeoutMs          int32 `protobuf:"varint,20,opt,name=listen_timeout_ms,json=listenTimeoutMs,proto3" json:"listen_timeout_ms,omitempty"`
	// --- M2 additions (numbers assigned once, never reused) ----------------
	RestartDelayMs int64  `protobuf:"varint,21,opt,name=restart_delay_ms,json=restartDelayMs,proto3" json:"restart_delay_ms,omitempty"` // default 0 = immediate restart (row 13)
	Namespace      string `protobuf:"bytes,22,opt,name=namespace,proto3" json:"namespace,omitempty"`                                    // default "default" (row 8)
	Treekill       bool   `protobuf:"varint,23,opt,name=treekill,proto3" json:"treekill,omitempty"`                                     // accepted; v1 always tree-kills (row 23 divergence)
	Time           bool   `protobuf:"varint,24,opt,name=time,proto3" json:"time,omitempty"`                                             // timestamps in logs (row 24)
	LogDateFormat  string `protobuf:"bytes,25,opt,name=log_date_format,json=logDateFormat,proto3" json:"log_date_format,omitempty"`     // row 25; empty = no timestamps
	OutFile        string `protobuf:"bytes,26,opt,name=out_file,json=outFile,proto3" json:"out_file,omitempty"`                         // rows 26-28: explicit sinks; empty = ~/.pm0 paths
	ErrorFile      string `protobuf:"bytes,27,opt,name=error_file,json=errorFile,proto3" json:"error_file,omitempty"`
	PidFile        string `protobuf:"bytes,28,opt,name=pid_file,json=pidFile,proto3" json:"pid_file,omitempty"`
	MergeLogs      bool   `protobuf:"varint,29,opt,name=merge_logs,json=mergeLogs,proto3" json:"merge_logs,omitempty"` // row 29: stderr into out file
	// Exit codes treated as intentional stops: the app parks stopped and is
	// NOT restarted (observed pm2 stop_exit_codes option).
	StopExitCodes []int32 `protobuf:"varint,30,rep,packed,name=stop_exit_codes,json=stopExitCodes,proto3" json:"stop_exit_codes,omitempty"`
	// --- M4 additions: built-in rotation knobs (divergence 12 config surface,
	// pm0 extension; NOT echoed in pm2_env) --------------------------------
	// Proto3 cannot distinguish "unset 0" from "explicit 0", and 0 means
	// "rotation off" in config memory — so the wire encodes three states:
	// 0 = default (10 MiB), -1 = rotation off, >0 = max bytes per sink before
	// copytruncate rotation.
	LogRotateMaxBytes int64 `protobuf:"varint,31,opt,name=log_rotate_max_bytes,json=logRotateMaxBytes,proto3" json:"log_rotate_max_bytes,omitempty"`
	// 0 = default (30 rotated copies retained); >0 = cap.
	LogRotateRetain int32 `protobuf:"varint,32,opt,name=log_rotate_retain,json=logRotateRetain,proto3" json:"log_rotate_retain,omitempty"`
	// --- M5 additions: health checks (divergence 7, pm0 extension; NOT
	// echoed in pm2_env). Cmd empty = off; 0 intervals lift to the pinned
	// defaults (30s / 5s / 3) at the daemon boundary, like the dump encoding.
	HealthCheckCmd        string `protobuf:"bytes,33,opt,name=health_check_cmd,json=healthCheckCmd,proto3" json:"health_check_cmd,omitempty"`                         // run via /bin/sh -c while the app is online
	HealthCheckIntervalMs int64  `protobuf:"varint,34,opt,name=health_check_interval_ms,json=healthCheckIntervalMs,proto3" json:"health_check_interval_ms,omitempty"` // 0 = default 30000
	HealthCheckTimeoutMs  int64  `protobuf:"varint,35,opt,name=health_check_timeout_ms,json=healthCheckTimeoutMs,proto3" json:"health_check_timeout_ms,omitempty"`    // 0 = default 5000 (clamped to interval)
	HealthCheckRetries    int32  `protobuf:"varint,36,opt,name=health_check_retries,json=healthCheckRetries,proto3" json:"health_check_retries,omitempty"`            // 0 = default 3 consecutive failures
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ProcessSpec) Reset() {
	*x = ProcessSpec{}
	mi := &file_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSpec) ProtoMessage() {}

func (x *ProcessSpec) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSpec.ProtoReflect.Descriptor instead.
func (*ProcessSpec) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessSpec) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ProcessSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProcessSpec) GetInterpreter() string {
	if x != nil {
		return x.Interpreter
	}
	return ""
}

func (x *ProcessSpec) GetInterpreterArgs() []string {
	if x != nil {
		return x.InterpreterArgs
	}
	return nil
}

func (x *ProcessSpec) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ProcessSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ProcessSpec) GetInstances() int32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

func (x *ProcessSpec) GetExecMode() string {
	if x != nil {
		return x.ExecMode
	}
	return ""
}

func (x *ProcessSpec) GetAutorestart() bool {
	if x != nil {
		return x.Autorestart
	}
	return false
}

func (x *ProcessSpec) GetKillSignal() string {
	if x != nil {
		return x.KillSignal
	}
	return ""
}

func (x *ProcessSpec) GetKillTimeoutMs() int32 {
	if x != nil {
		return x.KillTimeoutMs
	}
	return 0
}

func (x *ProcessSpec) GetMaxRestarts() int32 {
	if x != nil {
		return x.MaxRestarts
	}
	return 0
}

func (x *ProcessSpec) GetMinUptimeMs() int64 {
	if x != nil {
		return x.MinUptimeMs
	}
	return 0
}

func (x *ProcessSpec) GetMaxMemoryRestartBytes() int64 {
	if x != nil {
		return x.MaxMemoryRestartBytes
	}
	return 0
}

func (x *ProcessSpec) GetCronRestart() string {
	if x != nil {
		return x.CronRestart
	}
	return ""
}

func (x *ProcessSpec) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

func (x *ProcessSpec) GetExpBackoffRestartDelayMs() int64 {
	if x != nil {
		return x.ExpBackoffRestartDelayMs
	}
	return 0
}

func (x *ProcessSpec) GetWaitReady() bool {
	if x != nil {
		return x.WaitReady
	}
	return false
}

func (x *ProcessSpec) GetListenTimeoutMs() int32 {
	if x != nil {
		return x.ListenTimeoutMs
	}
	return 0
}

func (x *ProcessSpec) GetRestartDelayMs() int64 {
	if x != nil {
		return x.RestartDelayMs
	}
	return 0
}

func (x *ProcessSpec) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ProcessSpec) GetTreekill() bool {
	if x != nil {
		return x.Treekill
	}
	return false
}

func (x *ProcessSpec) GetTime() bool {
	if x != nil {
		return x.Time
	}
	return false
}

func (x *ProcessSpec) GetLogDateFormat() string {
	if x != nil {
		return x.LogDateFormat
	}
	return ""
}

func (x *ProcessSpec) GetOutFile() string {
	if x != nil {
		return x.OutFile
	}
	return ""
}

func (x *ProcessSpec) GetErrorFile() string {
	if x != nil {
		return x.ErrorFile
	}
	return ""
}

func (x *ProcessSpec) GetPidFile() string {
	if x != nil {
		return x.PidFile
	}
	return ""
}

func (x *ProcessSpec) GetMergeLogs() bool {
	if x != nil {
		return x.MergeLogs
	}
	return false
}

func (x *ProcessSpec) GetStopExitCodes() []int32 {
	if x != nil {
		return x.StopExitCodes
	}
	return nil
}

func (x *ProcessSpec) GetLogRotateMaxBytes() int64 {
	if x != nil {
		return x.LogRotateMaxBytes
	}
	return 0
}

func (x *ProcessSpec) GetLogRotateRetain() int32 {
	if x != nil {
		return x.LogRotateRetain
	}
	return 0
}

func (x *ProcessSpec) GetHealthCheckCmd() string {
	if x != nil {
		return x.HealthCheckCmd
	}
	return ""
}

func (x *ProcessSpec) GetHealthCheckIntervalMs() int64 {
	if x != nil {
		return x.HealthCheckIntervalMs
	}
	return 0
}

func (x *ProcessSpec) GetHealthCheckTimeoutMs() int64 {
	if x != nil {
		return x.HealthCheckTimeoutMs
	}
	return 0
}

func (x *ProcessSpec) GetHealthCheckRetries() int32 {
	if x != nil {
		return x.HealthCheckRetries
	}
	return 0
}

type StartProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specs         []*ProcessSpec         `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	mi := &file_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *StartProcessRequest) GetSpecs() []*ProcessSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

type StartProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	mi := &file_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *StartProcessResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type StopProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *Selector              `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProcessRequest) Reset() {
	*x = StopProcessRequest{}
	mi := &file_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessRequest) ProtoMessage() {}

func (x *StopProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessRequest.ProtoReflect.Descriptor instead.
func (*StopProcessRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *StopProcessRequest) GetSelector() *Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

type StopProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedPmIds []int32                `protobuf:"varint,1,rep,packed,name=affected_pm_ids,json=affectedPmIds,proto3" json:"affected_pm_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProcessResponse) Reset() {
	*x = StopProcessResponse{}
	mi := &file_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessResponse) ProtoMessage() {}

func (x *StopProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessResponse.ProtoReflect.Descriptor instead.
func (*StopProcessResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *StopProcessResponse) GetAffectedPmIds() []int32 {
	if x != nil {
		return x.AffectedPmIds
	}
	return nil
}

type RestartProcessRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Selector *Selector              `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	// Restart with an updated spec (env, args...). "pm0 restart app --update-env".
	UpdatedSpec   *ProcessSpec `protobuf:"bytes,2,opt,name=updated_spec,json=updatedSpec,proto3" json:"updated_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartProcessRequest) Reset() {
	*x = RestartProcessRequest{}
	mi := &file_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartProcessRequest) ProtoMessage() {}

func (x *RestartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartProcessRequest.ProtoReflect.Descriptor instead.
func (*RestartProcessRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *RestartProcessRequest) GetSelector() *Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *RestartProcessRequest) GetUpdatedSpec() *ProcessSpec {
	if x != nil {
		return x.UpdatedSpec
	}
	return nil
}

type RestartProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedPmIds []int32                `protobuf:"varint,1,rep,packed,name=affected_pm_ids,json=affectedPmIds,proto3" json:"affected_pm_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartProcessResponse) Reset() {
	*x = RestartProcessResponse{}
	mi := &file_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartProcessResponse) ProtoMessage() {}

func (x *RestartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartProcessResponse.ProtoReflect.Descriptor instead.
func (*RestartProcessResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *RestartProcessResponse) GetAffectedPmIds() []int32 {
	if x != nil {
		return x.AffectedPmIds
	}
	return nil
}

type DeleteProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *Selector              `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProcessRequest) Reset() {
	*x = DeleteProcessRequest{}
	mi := &file_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProcessRequest) ProtoMessage() {}

func (x *DeleteProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProcessRequest.ProtoReflect.Descriptor instead.
func (*DeleteProcessRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProcessRequest) GetSelector() *Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

type DeleteProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedPmIds []int32                `protobuf:"varint,1,rep,packed,name=affected_pm_ids,json=affectedPmIds,proto3" json:"affected_pm_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProcessResponse) Reset() {
	*x = DeleteProcessResponse{}
	mi := &file_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProcessResponse) ProtoMessage() {}

func (x *DeleteProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProcessResponse.ProtoReflect.Descriptor instead.
func (*DeleteProcessResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProcessResponse) GetAffectedPmIds() []int32 {
	if x != nil {
		return x.AffectedPmIds
	}
	return nil
}

type ReloadProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *Selector              `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadProcessRequest) Reset() {
	*x = ReloadProcessRequest{}
	mi := &file_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadProcessRequest) ProtoMessage() {}

func (x *ReloadProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadProcessRequest.ProtoReflect.Descriptor instead.
func (*ReloadProcessRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *ReloadProcessRequest) GetSelector() *Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

type ReloadProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedPmIds []int32                `protobuf:"varint,1,rep,packed,name=affected_pm_ids,json=affectedPmIds,proto3" json:"affected_pm_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadProcessResponse) Reset() {
	*x = ReloadProcessResponse{}
	mi := &file_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadProcessResponse) ProtoMessage() {}

func (x *ReloadProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadProcessResponse.ProtoReflect.Descriptor instead.
func (*ReloadProcessResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *ReloadProcessResponse) GetAffectedPmIds() []int32 {
	if x != nil {
		return x.AffectedPmIds
	}
	return nil
}

type ScaleProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"` // e.g. +2 or -1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleProcessRequest) Reset() {
	*x = ScaleProcessRequest{}
	mi := &file_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleProcessRequest) ProtoMessage() {}

func (x *ScaleProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleProcessRequest.ProtoReflect.Descriptor instead.
func (*ScaleProcessRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *ScaleProcessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScaleProcessRequest) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type ScaleProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedPmIds []int32                `protobuf:"varint,1,rep,packed,name=affected_pm_ids,json=affectedPmIds,proto3" json:"affected_pm_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleProcessResponse) Reset() {
	*x = ScaleProcessResponse{}
	mi := &file_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleProcessResponse) ProtoMessage() {}

func (x *ScaleProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleProcessResponse.ProtoReflect.Descriptor instead.
func (*ScaleProcessResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *ScaleProcessResponse) GetAffectedPmIds() []int32 {
	if x != nil {
		return x.AffectedPmIds
	}
	return nil
}

type ListProcessesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesRequest) Reset() {
	*x = ListProcessesRequest{}
	mi := &file_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesRequest) ProtoMessage() {}

func (x *ListProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesRequest.ProtoReflect.Descriptor instead.
func (*ListProcessesRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{16}
}

type ListProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *ListProcessesResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type DescribeProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *Selector              `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"` // must resolve to exactly one app
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeProcessRequest) Reset() {
	*x = DescribeProcessRequest{}
	mi := &file_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeProcessRequest) ProtoMessage() {}

func (x *DescribeProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeProcessRequest.ProtoReflect.Descriptor instead.
func (*DescribeProcessRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *DescribeProcessRequest) GetSelector() *Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

type DescribeProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       *ProcessInfo           `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeProcessResponse) Reset() {
	*x = DescribeProcessResponse{}
	mi := &file_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeProcessResponse) ProtoMessage() {}

func (x *DescribeProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeProcessResponse.ProtoReflect.Descriptor instead.
func (*DescribeProcessResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *DescribeProcessResponse) GetProcess() *ProcessInfo {
	if x != nil {
		return x.Process
	}
	return nil
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *Selector              `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Lines         int32                  `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`                                      // backlog size (ring buffer), 0 = live only
	IncludeStderr bool                   `protobuf:"varint,3,opt,name=include_stderr,json=includeStderr,proto3" json:"include_stderr,omitempty"` // CLI --err
	Raw           bool                   `protobuf:"varint,4,opt,name=raw,proto3" json:"raw,omitempty"`                                          // no prefix
	Follow        bool                   `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`                                    // false: send backlog and close
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *StreamLogsRequest) GetSelector() *Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *StreamLogsRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

func (x *StreamLogsRequest) GetIncludeStderr() bool {
	if x != nil {
		return x.IncludeStderr
	}
	return false
}

func (x *StreamLogsRequest) GetRaw() bool {
	if x != nil {
		return x.Raw
	}
	return false
}

func (x *StreamLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PmId          int32                  `protobuf:"varint,1,opt,name=pm_id,json=pmId,proto3" json:"pm_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stream        LogLine_Stream         `protobuf:"varint,3,opt,name=stream,proto3,enum=pm0.v1.LogLine_Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // 0 = timestamps disabled (PM2 default: off)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *LogLine) GetPmId() int32 {
	if x != nil {
		return x.PmId
	}
	return 0
}

func (x *LogLine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogLine) GetStream() LogLine_Stream {
	if x != nil {
		return x.Stream
	}
	return LogLine_STREAM_UNSPECIFIED
}

func (x *LogLine) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogLine) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type SaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_daemon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{22}
}

type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DumpPath      string                 `protobuf:"bytes,1,opt,name=dump_path,json=dumpPath,proto3" json:"dump_path,omitempty"` // ~/.pm0/dump.json
	SavedCount    int32                  `protobuf:"varint,2,opt,name=saved_count,json=savedCount,proto3" json:"saved_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_daemon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *SaveResponse) GetDumpPath() string {
	if x != nil {
		return x.DumpPath
	}
	return ""
}

func (x *SaveResponse) GetSavedCount() int32 {
	if x != nil {
		return x.SavedCount
	}
	return 0
}

type ResurrectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResurrectRequest) Reset() {
	*x = ResurrectRequest{}
	mi := &file_daemon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResurrectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResurrectRequest) ProtoMessage() {}

func (x *ResurrectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResurrectRequest.ProtoReflect.Descriptor instead.
func (*ResurrectRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{24}
}

type ResurrectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartedCount  int32                  `protobuf:"varint,1,opt,name=started_count,json=startedCount,proto3" json:"started_count,omitempty"`
	ErroredCount  int32                  `protobuf:"varint,2,opt,name=errored_count,json=erroredCount,proto3" json:"errored_count,omitempty"` // missing binary etc. — never aborts the batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResurrectResponse) Reset() {
	*x = ResurrectResponse{}
	mi := &file_daemon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResurrectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResurrectResponse) ProtoMessage() {}

func (x *ResurrectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResurrectResponse.ProtoReflect.Descriptor instead.
func (*ResurrectResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{25}
}

func (x *ResurrectResponse) GetStartedCount() int32 {
	if x != nil {
		return x.StartedCount
	}
	return 0
}

func (x *ResurrectResponse) GetErroredCount() int32 {
	if x != nil {
		return x.ErroredCount
	}
	return 0
}

type UpdateDaemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDaemonRequest) Reset() {
	*x = UpdateDaemonRequest{}
	mi := &file_daemon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDaemonRequest) ProtoMessage() {}

func (x *UpdateDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDaemonRequest.ProtoReflect.Descriptor instead.
func (*UpdateDaemonRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{26}
}

type UpdateDaemonEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"` // "saving" | "re-execing"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDaemonEvent) Reset() {
	*x = UpdateDaemonEvent{}
	mi := &file_daemon_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDaemonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDaemonEvent) ProtoMessage() {}

func (x *UpdateDaemonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDaemonEvent.ProtoReflect.Descriptor instead.
func (*UpdateDaemonEvent) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateDaemonEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

type KillDaemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"` // true: do not stop apps first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillDaemonRequest) Reset() {
	*x = KillDaemonRequest{}
	mi := &file_daemon_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillDaemonRequest) ProtoMessage() {}

func (x *KillDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillDaemonRequest.ProtoReflect.Descriptor instead.
func (*KillDaemonRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{28}
}

func (x *KillDaemonRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type KillDaemonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillDaemonResponse) Reset() {
	*x = KillDaemonResponse{}
	mi := &file_daemon_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillDaemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillDaemonResponse) ProtoMessage() {}

func (x *KillDaemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillDaemonResponse.ProtoReflect.Descriptor instead.
func (*KillDaemonResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{29}
}

// Monit carries the `monit` object of jlist. memory is RSS of the process
// tree (cgroup memory.stat anon or per-proc RSS sum) — NOT memory.current,
// which page cache inflates vs pm2 (docs/compat.md).
type Monit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        int64                  `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"` // bytes
	Cpu           float64                `protobuf:"fixed64,2,opt,name=cpu,proto3" json:"cpu,omitempty"`      // percent of one core
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Monit) Reset() {
	*x = Monit{}
	mi := &file_daemon_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monit) ProtoMessage() {}

func (x *Monit) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monit.ProtoReflect.Descriptor instead.
func (*Monit) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{30}
}

func (x *Monit) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Monit) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

// ProcessEnv mirrors the pm2_env object of jlist. PM2 dumps the full child
// environment in env — a known secrets exposure kept for compat; the daemon
// supports --redact-env (docs/compat.md).
type ProcessEnv struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace             string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PmId                  int32                  `protobuf:"varint,3,opt,name=pm_id,json=pmId,proto3" json:"pm_id,omitempty"`
	PmExecPath            string                 `protobuf:"bytes,4,opt,name=pm_exec_path,json=pmExecPath,proto3" json:"pm_exec_path,omitempty"` // resolved script
	Args                  []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	PmCwd                 string                 `protobuf:"bytes,6,opt,name=pm_cwd,json=pmCwd,proto3" json:"pm_cwd,omitempty"`
	PmOutLogPath          string                 `protobuf:"bytes,7,opt,name=pm_out_log_path,json=pmOutLogPath,proto3" json:"pm_out_log_path,omitempty"`
	PmErrLogPath          string                 `protobuf:"bytes,8,opt,name=pm_err_log_path,json=pmErrLogPath,proto3" json:"pm_err_log_path,omitempty"`
	PmPidPath             string                 `protobuf:"bytes,9,opt,name=pm_pid_path,json=pmPidPath,proto3" json:"pm_pid_path,omitempty"`
	Interpreter           string                 `protobuf:"bytes,10,opt,name=interpreter,proto3" json:"interpreter,omitempty"`
	InterpreterArgs       []string               `protobuf:"bytes,11,rep,name=interpreter_args,json=interpreterArgs,proto3" json:"interpreter_args,omitempty"`
	ExecMode              string                 `protobuf:"bytes,12,opt,name=exec_mode,json=execMode,proto3" json:"exec_mode,omitempty"` // "fork" | "cluster"
	Instances             int32                  `protobuf:"varint,13,opt,name=instances,proto3" json:"instances,omitempty"`
	KillSignal            string                 `protobuf:"bytes,14,opt,name=kill_signal,json=killSignal,proto3" json:"kill_signal,omitempty"`
	KillTimeoutMs         int32                  `protobuf:"varint,15,opt,name=kill_timeout_ms,json=killTimeoutMs,proto3" json:"kill_timeout_ms,omitempty"`
	Autorestart           bool                   `protobuf:"varint,16,opt,name=autorestart,proto3" json:"autorestart,omitempty"`
	MaxRestarts           int32                  `protobuf:"varint,17,opt,name=max_restarts,json=maxRestarts,proto3" json:"max_restarts,omitempty"`
	MinUptimeMs           int64                  `protobuf:"varint,18,opt,name=min_uptime_ms,json=minUptimeMs,proto3" json:"min_uptime_ms,omitempty"`
	MaxMemoryRestartBytes int64                  `protobuf:"varint,19,opt,name=max_memory_restart_bytes,json=maxMemoryRestartBytes,proto3" json:"max_memory_restart_bytes,omitempty"`
	RestartTime           int32                  `protobuf:"varint,20,opt,name=restart_time,json=restartTime,proto3" json:"restart_time,omitempty"` // successful restart counter
	UnstableRestarts      int32                  `protobuf:"varint,21,opt,name=unstable_restarts,json=unstableRestarts,proto3" json:"unstable_restarts,omitempty"`
	CreatedAt             int64                  `protobuf:"varint,22,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // epoch ms
	PmUptime              int64                  `protobuf:"varint,23,opt,name=pm_uptime,json=pmUptime,proto3" json:"pm_uptime,omitempty"`    // epoch ms of last start
	ExitCode              int32                  `protobuf:"varint,24,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`    // last exit code
	WaitReady             bool                   `protobuf:"varint,25,opt,name=wait_ready,json=waitReady,proto3" json:"wait_ready,omitempty"`
	ListenTimeoutMs       int32                  `protobuf:"varint,26,opt,name=listen_timeout_ms,json=listenTimeoutMs,proto3" json:"listen_timeout_ms,omitempty"`
	CronRestart           string                 `protobuf:"bytes,27,opt,name=cron_restart,json=cronRestart,proto3" json:"cron_restart,omitempty"`
	Watch                 bool                   `protobuf:"varint,28,opt,name=watch,proto3" json:"watch,omitempty"`
	ExpBackoffRestartTime bool                   `protobuf:"varint,29,opt,name=exp_backoff_restart_time,json=expBackoffRestartTime,proto3" json:"exp_backoff_restart_time,omitempty"`
	Env                   map[string]string      `protobuf:"bytes,30,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// --- M2 additions -------------------------------------------------------
	Treekill      bool   `protobuf:"varint,31,opt,name=treekill,proto3" json:"treekill,omitempty"`                                 // always true in v1 (row 23 divergence)
	Time          bool   `protobuf:"varint,32,opt,name=time,proto3" json:"time,omitempty"`                                         // timestamps flag echo (row 24)
	MergeLogs     bool   `protobuf:"varint,33,opt,name=merge_logs,json=mergeLogs,proto3" json:"merge_logs,omitempty"`              // row 29
	LogDateFormat string `protobuf:"bytes,34,opt,name=log_date_format,json=logDateFormat,proto3" json:"log_date_format,omitempty"` // row 25
	// §2.2: exit_code is JSON null while running / on signal deaths. proto3
	// int32 cannot be null, so presence rides alongside (false => render null).
	ExitCodePresent bool  `protobuf:"varint,35,opt,name=exit_code_present,json=exitCodePresent,proto3" json:"exit_code_present,omitempty"`
	RestartDelayMs  int64 `protobuf:"varint,36,opt,name=restart_delay_ms,json=restartDelayMs,proto3" json:"restart_delay_ms,omitempty"` // row 13 echo
	// created_at is JSON null after a crash-loop parks the app errored
	// (observed pm2 sets created_at = null there); presence rides alongside.
	CreatedAtPresent         bool    `protobuf:"varint,37,opt,name=created_at_present,json=createdAtPresent,proto3" json:"created_at_present,omitempty"`
	ExpBackoffRestartDelayMs int64   `protobuf:"varint,38,opt,name=exp_backoff_restart_delay_ms,json=expBackoffRestartDelayMs,proto3" json:"exp_backoff_restart_delay_ms,omitempty"` // observed pm2 option echo
	StopExitCodes            []int32 `protobuf:"varint,39,rep,packed,name=stop_exit_codes,json=stopExitCodes,proto3" json:"stop_exit_codes,omitempty"`                               // observed pm2 option echo
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ProcessEnv) Reset() {
	*x = ProcessEnv{}
	mi := &file_daemon_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEnv) ProtoMessage() {}

func (x *ProcessEnv) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEnv.ProtoReflect.Descriptor instead.
func (*ProcessEnv) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{31}
}

func (x *ProcessEnv) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessEnv) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ProcessEnv) GetPmId() int32 {
	if x != nil {
		return x.PmId
	}
	return 0
}

func (x *ProcessEnv) GetPmExecPath() string {
	if x != nil {
		return x.PmExecPath
	}
	return ""
}

func (x *ProcessEnv) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProcessEnv) GetPmCwd() string {
	if x != nil {
		return x.PmCwd
	}
	return ""
}

func (x *ProcessEnv) GetPmOutLogPath() string {
	if x != nil {
		return x.PmOutLogPath
	}
	return ""
}

func (x *ProcessEnv) GetPmErrLogPath() string {
	if x != nil {
		return x.PmErrLogPath
	}
	return ""
}

func (x *ProcessEnv) GetPmPidPath() string {
	if x != nil {
		return x.PmPidPath
	}
	return ""
}

func (x *ProcessEnv) GetInterpreter() string {
	if x != nil {
		return x.Interpreter
	}
	return ""
}

func (x *ProcessEnv) GetInterpreterArgs() []string {
	if x != nil {
		return x.InterpreterArgs
	}
	return nil
}

func (x *ProcessEnv) GetExecMode() string {
	if x != nil {
		return x.ExecMode
	}
	return ""
}

func (x *ProcessEnv) GetInstances() int32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

func (x *ProcessEnv) GetKillSignal() string {
	if x != nil {
		return x.KillSignal
	}
	return ""
}

func (x *ProcessEnv) GetKillTimeoutMs() int32 {
	if x != nil {
		return x.KillTimeoutMs
	}
	return 0
}

func (x *ProcessEnv) GetAutorestart() bool {
	if x != nil {
		return x.Autorestart
	}
	return false
}

func (x *ProcessEnv) GetMaxRestarts() int32 {
	if x != nil {
		return x.MaxRestarts
	}
	return 0
}

func (x *ProcessEnv) GetMinUptimeMs() int64 {
	if x != nil {
		return x.MinUptimeMs
	}
	return 0
}

func (x *ProcessEnv) GetMaxMemoryRestartBytes() int64 {
	if x != nil {
		return x.MaxMemoryRestartBytes
	}
	return 0
}

func (x *ProcessEnv) GetRestartTime() int32 {
	if x != nil {
		return x.RestartTime
	}
	return 0
}

func (x *ProcessEnv) GetUnstableRestarts() int32 {
	if x != nil {
		return x.UnstableRestarts
	}
	return 0
}

func (x *ProcessEnv) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ProcessEnv) GetPmUptime() int64 {
	if x != nil {
		return x.PmUptime
	}
	return 0
}

func (x *ProcessEnv) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ProcessEnv) GetWaitReady() bool {
	if x != nil {
		return x.WaitReady
	}
	return false
}

func (x *ProcessEnv) GetListenTimeoutMs() int32 {
	if x != nil {
		return x.ListenTimeoutMs
	}
	return 0
}

func (x *ProcessEnv) GetCronRestart() string {
	if x != nil {
		return x.CronRestart
	}
	return ""
}

func (x *ProcessEnv) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

func (x *ProcessEnv) GetExpBackoffRestartTime() bool {
	if x != nil {
		return x.ExpBackoffRestartTime
	}
	return false
}

func (x *ProcessEnv) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ProcessEnv) GetTreekill() bool {
	if x != nil {
		return x.Treekill
	}
	return false
}

func (x *ProcessEnv) GetTime() bool {
	if x != nil {
		return x.Time
	}
	return false
}

func (x *ProcessEnv) GetMergeLogs() bool {
	if x != nil {
		return x.MergeLogs
	}
	return false
}

func (x *ProcessEnv) GetLogDateFormat() string {
	if x != nil {
		return x.LogDateFormat
	}
	return ""
}

func (x *ProcessEnv) GetExitCodePresent() bool {
	if x != nil {
		return x.ExitCodePresent
	}
	return false
}

func (x *ProcessEnv) GetRestartDelayMs() int64 {
	if x != nil {
		return x.RestartDelayMs
	}
	return 0
}

func (x *ProcessEnv) GetCreatedAtPresent() bool {
	if x != nil {
		return x.CreatedAtPresent
	}
	return false
}

func (x *ProcessEnv) GetExpBackoffRestartDelayMs() int64 {
	if x != nil {
		return x.ExpBackoffRestartDelayMs
	}
	return 0
}

func (x *ProcessEnv) GetStopExitCodes() []int32 {
	if x != nil {
		return x.StopExitCodes
	}
	return nil
}

// ProcessInfo mirrors the top-level jlist entry. The M2 JSON layer renders
// { pid, pm_id, name, monit, pm2_env } with exact PM2 key names; this message
// is the typed backing store, not the wire-JSON shape itself.
type ProcessInfo struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	PmId   int32                  `protobuf:"varint,1,opt,name=pm_id,json=pmId,proto3" json:"pm_id,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pid    int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"` // 0 when not running
	Status ProcessStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=pm0.v1.ProcessStatus" json:"status,omitempty"`
	Monit  *Monit                 `protobuf:"bytes,5,opt,name=monit,proto3" json:"monit,omitempty"`
	Pm2Env *ProcessEnv            `protobuf:"bytes,6,opt,name=pm2_env,json=pm2Env,proto3" json:"pm2_env,omitempty"`
	// pm0 extension (divergence 6, M5): "oom" when the last death was a
	// kernel OOM kill (wait status SIGKILL + cgroup memory.events oom_kill
	// advance), "" otherwise. Additive observability; describe-only.
	ExitReason    string `protobuf:"bytes,7,opt,name=exit_reason,json=exitReason,proto3" json:"exit_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_daemon_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{32}
}

func (x *ProcessInfo) GetPmId() int32 {
	if x != nil {
		return x.PmId
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetStatus() ProcessStatus {
	if x != nil {
		return x.Status
	}
	return ProcessStatus_PROCESS_STATUS_UNSPECIFIED
}

func (x *ProcessInfo) GetMonit() *Monit {
	if x != nil {
		return x.Monit
	}
	return nil
}

func (x *ProcessInfo) GetPm2Env() *ProcessEnv {
	if x != nil {
		return x.Pm2Env
	}
	return nil
}

func (x *ProcessInfo) GetExitReason() string {
	if x != nil {
		return x.ExitReason
	}
	return ""
}

var File_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_rawDesc = "" +
	"\n" +
	"\fdaemon.proto\x12\x06pm0.v1\"I\n" +
	"\bSelector\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x12\x15\n" +
	"\x06pm_ids\x18\x02 \x03(\x05R\x05pmIds\x12\x10\n" +
	"\x03all\x18\x03 \x01(\bR\x03all\"\r\n" +
	"\vPingRequest\"\xbd\x01\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1b\n" +
	"\tkill_mode\x18\x04 \x01(\tR\bkillMode\x12%\n" +
	"\x0ekernel_release\x18\x05 \x01(\tR\rkernelRelease\x12%\n" +
	"\x0ecgroup_warning\x18\x06 \x01(\tR\rcgroupWarning\"\xe3\n" +
	"\n" +
	"\vProcessSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12 \n" +
	"\vinterpreter\x18\x04 \x01(\tR\vinterpreter\x12)\n" +
	"\x10interpreter_args\x18\x05 \x03(\tR\x0finterpreterArgs\x12\x10\n" +
	"\x03cwd\x18\x06 \x01(\tR\x03cwd\x12.\n" +
	"\x03env\x18\a \x03(\v2\x1c.pm0.v1.ProcessSpec.EnvEntryR\x03env\x12\x1c\n" +
	"\tinstances\x18\b \x01(\x05R\tinstances\x12\x1b\n" +
	"\texec_mode\x18\t \x01(\tR\bexecMode\x12 \n" +
	"\vautorestart\x18\n" +
	" \x01(\bR\vautorestart\x12\x1f\n" +
	"\vkill_signal\x18\v \x01(\tR\n" +
	"killSignal\x12&\n" +
	"\x0fkill_timeout_ms\x18\f \x01(\x05R\rkillTimeoutMs\x12!\n" +
	"\fmax_restarts\x18\r \x01(\x05R\vmaxRestarts\x12\"\n" +
	"\rmin_uptime_ms\x18\x0e \x01(\x03R\vminUptimeMs\x127\n" +
	"\x18max_memory_restart_bytes\x18\x0f \x01(\x03R\x15maxMemoryRestartBytes\x12!\n" +
	"\fcron_restart\x18\x10 \x01(\tR\vcronRestart\x12\x14\n" +
	"\x05watch\x18\x11 \x01(\bR\x05watch\x12>\n" +
	"\x1cexp_backoff_restart_delay_ms\x18\x12 \x01(\x03R\x18expBackoffRestartDelayMs\x12\x1d\n" +
	"\n" +
	"wait_ready\x18\x13 \x01(\bR\twaitReady\x12*\n" +
	"\x11listen_timeout_ms\x18\x14 \x01(\x05R\x0flistenTimeoutMs\x12(\n" +
	"\x10restart_delay_ms\x18\x15 \x01(\x03R\x0erestartDelayMs\x12\x1c\n" +
	"\tnamespace\x18\x16 \x01(\tR\tnamespace\x12\x1a\n" +
	"\btreekill\x18\x17 \x01(\bR\btreekill\x12\x12\n" +
	"\x04time\x18\x18 \x01(\bR\x04time\x12&\n" +
	"\x0flog_date_format\x18\x19 \x01(\tR\rlogDateFormat\x12\x19\n" +
	"\bout_file\x18\x1a \x01(\tR\aoutFile\x12\x1d\n" +
	"\n" +
	"error_file\x18\x1b \x01(\tR\terrorFile\x12\x19\n" +
	"\bpid_file\x18\x1c \x01(\tR\apidFile\x12\x1d\n" +
	"\n" +
	"merge_logs\x18\x1d \x01(\bR\tmergeLogs\x12&\n" +
	"\x0fstop_exit_codes\x18\x1e \x03(\x05R\rstopExitCodes\x12/\n" +
	"\x14log_rotate_max_bytes\x18\x1f \x01(\x03R\x11logRotateMaxBytes\x12*\n" +
	"\x11log_rotate_retain\x18  \x01(\x05R\x0flogRotateRetain\x12(\n" +
	"\x10health_check_cmd\x18! \x01(\tR\x0ehealthCheckCmd\x127\n" +
	"\x18health_check_interval_ms\x18\" \x01(\x03R\x15healthCheckIntervalMs\x125\n" +
	"\x17health_check_timeout_ms\x18# \x01(\x03R\x14healthCheckTimeoutMs\x120\n" +
	"\x14health_check_retries\x18$ \x01(\x05R\x12healthCheckRetries\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x13StartProcessRequest\x12)\n" +
	"\x05specs\x18\x01 \x03(\v2\x13.pm0.v1.ProcessSpecR\x05specs\"I\n" +
	"\x14StartProcessResponse\x121\n" +
	"\tprocesses\x18\x01 \x03(\v2\x13.pm0.v1.ProcessInfoR\tprocesses\"B\n" +
	"\x12StopProcessRequest\x12,\n" +
	"\bselector\x18\x01 \x01(\v2\x10.pm0.v1.SelectorR\bselector\"=\n" +
	"\x13StopProcessResponse\x12&\n" +
	"\x0faffected_pm_ids\x18\x01 \x03(\x05R\raffectedPmIds\"}\n" +
	"\x15RestartProcessRequest\x12,\n" +
	"\bselector\x18\x01 \x01(\v2\x10.pm0.v1.SelectorR\bselector\x126\n" +
	"\fupdated_spec\x18\x02 \x01(\v2\x13.pm0.v1.ProcessSpecR\vupdatedSpec\"@\n" +
	"\x16RestartProcessResponse\x12&\n" +
	"\x0faffected_pm_ids\x18\x01 \x03(\x05R\raffectedPmIds\"D\n" +
	"\x14DeleteProcessRequest\x12,\n" +
	"\bselector\x18\x01 \x01(\v2\x10.pm0.v1.SelectorR\bselector\"?\n" +
	"\x15DeleteProcessResponse\x12&\n" +
	"\x0faffected_pm_ids\x18\x01 \x03(\x05R\raffectedPmIds\"D\n" +
	"\x14ReloadProcessRequest\x12,\n" +
	"\bselector\x18\x01 \x01(\v2\x10.pm0.v1.SelectorR\bselector\"?\n" +
	"\x15ReloadProcessResponse\x12&\n" +
	"\x0faffected_pm_ids\x18\x01 \x03(\x05R\raffectedPmIds\"?\n" +
	"\x13ScaleProcessRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\">\n" +
	"\x14ScaleProcessResponse\x12&\n" +
	"\x0faffected_pm_ids\x18\x01 \x03(\x05R\raffectedPmIds\"\x16\n" +
	"\x14ListProcessesRequest\"J\n" +
	"\x15ListProcessesResponse\x121\n" +
	"\tprocesses\x18\x01 \x03(\v2\x13.pm0.v1.ProcessInfoR\tprocesses\"F\n" +
	"\x16DescribeProcessRequest\x12,\n" +
	"\bselector\x18\x01 \x01(\v2\x10.pm0.v1.SelectorR\bselector\"H\n" +
	"\x17DescribeProcessResponse\x12-\n" +
	"\aprocess\x18\x01 \x01(\v2\x13.pm0.v1.ProcessInfoR\aprocess\"\xa8\x01\n" +
	"\x11StreamLogsRequest\x12,\n" +
	"\bselector\x18\x01 \x01(\v2\x10.pm0.v1.SelectorR\bselector\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\x05R\x05lines\x12%\n" +
	"\x0einclude_stderr\x18\x03 \x01(\bR\rincludeStderr\x12\x10\n" +
	"\x03raw\x18\x04 \x01(\bR\x03raw\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\"\xe1\x01\n" +
	"\aLogLine\x12\x13\n" +
	"\x05pm_id\x18\x01 \x01(\x05R\x04pmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x06stream\x18\x03 \x01(\x0e2\x16.pm0.v1.LogLine.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\"F\n" +
	"\x06Stream\x12\x16\n" +
	"\x12STREAM_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTREAM_STDOUT\x10\x01\x12\x11\n" +
	"\rSTREAM_STDERR\x10\x02\"\r\n" +
	"\vSaveRequest\"L\n" +
	"\fSaveResponse\x12\x1b\n" +
	"\tdump_path\x18\x01 \x01(\tR\bdumpPath\x12\x1f\n" +
	"\vsaved_count\x18\x02 \x01(\x05R\n" +
	"savedCount\"\x12\n" +
	"\x10ResurrectRequest\"]\n" +
	"\x11ResurrectResponse\x12#\n" +
	"\rstarted_count\x18\x01 \x01(\x05R\fstartedCount\x12#\n" +
	"\rerrored_count\x18\x02 \x01(\x05R\ferroredCount\"\x15\n" +
	"\x13UpdateDaemonRequest\")\n" +
	"\x11UpdateDaemonEvent\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\")\n" +
	"\x11KillDaemonRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"\x14\n" +
	"\x12KillDaemonResponse\"1\n" +
	"\x05Monit\x12\x16\n" +
	"\x06memory\x18\x01 \x01(\x03R\x06memory\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\x01R\x03cpu\"\xb1\v\n" +
	"\n" +
	"ProcessEnv\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x13\n" +
	"\x05pm_id\x18\x03 \x01(\x05R\x04pmId\x12 \n" +
	"\fpm_exec_path\x18\x04 \x01(\tR\n" +
	"pmExecPath\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12\x15\n" +
	"\x06pm_cwd\x18\x06 \x01(\tR\x05pmCwd\x12%\n" +
	"\x0fpm_out_log_path\x18\a \x01(\tR\fpmOutLogPath\x12%\n" +
	"\x0fpm_err_log_path\x18\b \x01(\tR\fpmErrLogPath\x12\x1e\n" +
	"\vpm_pid_path\x18\t \x01(\tR\tpmPidPath\x12 \n" +
	"\vinterpreter\x18\n" +
	" \x01(\tR\vinterpreter\x12)\n" +
	"\x10interpreter_args\x18\v \x03(\tR\x0finterpreterArgs\x12\x1b\n" +
	"\texec_mode\x18\f \x01(\tR\bexecMode\x12\x1c\n" +
	"\tinstances\x18\r \x01(\x05R\tinstances\x12\x1f\n" +
	"\vkill_signal\x18\x0e \x01(\tR\n" +
	"killSignal\x12&\n" +
	"\x0fkill_timeout_ms\x18\x0f \x01(\x05R\rkillTimeoutMs\x12 \n" +
	"\vautorestart\x18\x10 \x01(\bR\vautorestart\x12!\n" +
	"\fmax_restarts\x18\x11 \x01(\x05R\vmaxRestarts\x12\"\n" +
	"\rmin_uptime_ms\x18\x12 \x01(\x03R\vminUptimeMs\x127\n" +
	"\x18max_memory_restart_bytes\x18\x13 \x01(\x03R\x15maxMemoryRestartBytes\x12!\n" +
	"\frestart_time\x18\x14 \x01(\x05R\vrestartTime\x12+\n" +
	"\x11unstable_restarts\x18\x15 \x01(\x05R\x10unstableRestarts\x12\x1d\n" +
	"\n" +
	"created_at\x18\x16 \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tpm_uptime\x18\x17 \x01(\x03R\bpmUptime\x12\x1b\n" +
	"\texit_code\x18\x18 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"wait_ready\x18\x19 \x01(\bR\twaitReady\x12*\n" +
	"\x11listen_timeout_ms\x18\x1a \x01(\x05R\x0flistenTimeoutMs\x12!\n" +
	"\fcron_restart\x18\x1b \x01(\tR\vcronRestart\x12\x14\n" +
	"\x05watch\x18\x1c \x01(\bR\x05watch\x127\n" +
	"\x18exp_backoff_restart_time\x18\x1d \x01(\bR\x15expBackoffRestartTime\x12-\n" +
	"\x03env\x18\x1e \x03(\v2\x1b.pm0.v1.ProcessEnv.EnvEntryR\x03env\x12\x1a\n" +
	"\btreekill\x18\x1f \x01(\bR\btreekill\x12\x12\n" +
	"\x04time\x18  \x01(\bR\x04time\x12\x1d\n" +
	"\n" +
	"merge_logs\x18! \x01(\bR\tmergeLogs\x12&\n" +
	"\x0flog_date_format\x18\" \x01(\tR\rlogDateFormat\x12*\n" +
	"\x11exit_code_present\x18# \x01(\bR\x0fexitCodePresent\x12(\n" +
	"\x10restart_delay_ms\x18$ \x01(\x03R\x0erestartDelayMs\x12,\n" +
	"\x12created_at_present\x18% \x01(\bR\x10createdAtPresent\x12>\n" +
	"\x1cexp_backoff_restart_delay_ms\x18& \x01(\x03R\x18expBackoffRestartDelayMs\x12&\n" +
	"\x0fstop_exit_codes\x18' \x03(\x05R\rstopExitCodes\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xea\x01\n" +
	"\vProcessInfo\x12\x13\n" +
	"\x05pm_id\x18\x01 \x01(\x05R\x04pmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.pm0.v1.ProcessStatusR\x06status\x12#\n" +
	"\x05monit\x18\x05 \x01(\v2\r.pm0.v1.MonitR\x05monit\x12+\n" +
	"\apm2_env\x18\x06 \x01(\v2\x12.pm0.v1.ProcessEnvR\x06pm2Env\x12\x1f\n" +
	"\vexit_reason\x18\a \x01(\tR\n" +
	"exitReason*\xd9\x01\n" +
	"\rProcessStatus\x12\x1e\n" +
	"\x1aPROCESS_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PROCESS_STATUS_LAUNCHING\x10\x01\x12\x19\n" +
	"\x15PROCESS_STATUS_ONLINE\x10\x02\x12\x1a\n" +
	"\x16PROCESS_STATUS_STOPPED\x10\x03\x12\x1b\n" +
	"\x17PROCESS_STATUS_STOPPING\x10\x04\x12\x1a\n" +
	"\x16PROCESS_STATUS_WAITING\x10\x05\x12\x1a\n" +
	"\x16PROCESS_STATUS_ERRORED\x10\x062\xe8\a\n" +
	"\x06Daemon\x121\n" +
	"\x04Ping\x12\x13.pm0.v1.PingRequest\x1a\x14.pm0.v1.PingResponse\x12I\n" +
	"\fStartProcess\x12\x1b.pm0.v1.StartProcessRequest\x1a\x1c.pm0.v1.StartProcessResponse\x12F\n" +
	"\vStopProcess\x12\x1a.pm0.v1.StopProcessRequest\x1a\x1b.pm0.v1.StopProcessResponse\x12O\n" +
	"\x0eRestartProcess\x12\x1d.pm0.v1.RestartProcessRequest\x1a\x1e.pm0.v1.RestartProcessResponse\x12L\n" +
	"\rDeleteProcess\x12\x1c.pm0.v1.DeleteProcessRequest\x1a\x1d.pm0.v1.DeleteProcessResponse\x12L\n" +
	"\rReloadProcess\x12\x1c.pm0.v1.ReloadProcessRequest\x1a\x1d.pm0.v1.ReloadProcessResponse\x12I\n" +
	"\fScaleProcess\x12\x1b.pm0.v1.ScaleProcessRequest\x1a\x1c.pm0.v1.ScaleProcessResponse\x12L\n" +
	"\rListProcesses\x12\x1c.pm0.v1.ListProcessesRequest\x1a\x1d.pm0.v1.ListProcessesResponse\x12R\n" +
	"\x0fDescribeProcess\x12\x1e.pm0.v1.DescribeProcessRequest\x1a\x1f.pm0.v1.DescribeProcessResponse\x12:\n" +
	"\n" +
	"StreamLogs\x12\x19.pm0.v1.StreamLogsRequest\x1a\x0f.pm0.v1.LogLine0\x01\x121\n" +
	"\x04Save\x12\x13.pm0.v1.SaveRequest\x1a\x14.pm0.v1.SaveResponse\x12@\n" +
	"\tResurrect\x12\x18.pm0.v1.ResurrectRequest\x1a\x19.pm0.v1.ResurrectResponse\x12H\n" +
	"\fUpdateDaemon\x12\x1b.pm0.v1.UpdateDaemonRequest\x1a\x19.pm0.v1.UpdateDaemonEvent0\x01\x12C\n" +
	"\n" +
	"KillDaemon\x12\x19.pm0.v1.KillDaemonRequest\x1a\x1a.pm0.v1.KillDaemonResponseB\x1eZ\x1cgithub.com/pm0/pm0/api/v1;v1b\x06proto3"

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData []byte
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_daemon_proto_goTypes = []any{
	(ProcessStatus)(0),              // 0: pm0.v1.ProcessStatus
	(LogLine_Stream)(0),             // 1: pm0.v1.LogLine.Stream
	(*Selector)(nil),                // 2: pm0.v1.Selector
	(*PingRequest)(nil),             // 3: pm0.v1.PingRequest
	(*PingResponse)(nil),            // 4: pm0.v1.PingResponse
	(*ProcessSpec)(nil),             // 5: pm0.v1.ProcessSpec
	(*StartProcessRequest)(nil),     // 6: pm0.v1.StartProcessRequest
	(*StartProcessResponse)(nil),    // 7: pm0.v1.StartProcessResponse
	(*StopProcessRequest)(nil),      // 8: pm0.v1.StopProcessRequest
	(*StopProcessResponse)(nil),     // 9: pm0.v1.StopProcessResponse
	(*RestartProcessRequest)(nil),   // 10: pm0.v1.RestartProcessRequest
	(*RestartProcessResponse)(nil),  // 11: pm0.v1.RestartProcessResponse
	(*DeleteProcessRequest)(nil),    // 12: pm0.v1.DeleteProcessRequest
	(*DeleteProcessResponse)(nil),   // 13: pm0.v1.DeleteProcessResponse
	(*ReloadProcessRequest)(nil),    // 14: pm0.v1.ReloadProcessRequest
	(*ReloadProcessResponse)(nil),   // 15: pm0.v1.ReloadProcessResponse
	(*ScaleProcessRequest)(nil),     // 16: pm0.v1.ScaleProcessRequest
	(*ScaleProcessResponse)(nil),    // 17: pm0.v1.ScaleProcessResponse
	(*ListProcessesRequest)(nil),    // 18: pm0.v1.ListProcessesRequest
	(*ListProcessesResponse)(nil),   // 19: pm0.v1.ListProcessesResponse
	(*DescribeProcessRequest)(nil),  // 20: pm0.v1.DescribeProcessRequest
	(*DescribeProcessResponse)(nil), // 21: pm0.v1.DescribeProcessResponse
	(*StreamLogsRequest)(nil),       // 22: pm0.v1.StreamLogsRequest
	(*LogLine)(nil),                 // 23: pm0.v1.LogLine
	(*SaveRequest)(nil),             // 24: pm0.v1.SaveRequest
	(*SaveResponse)(nil),            // 25: pm0.v1.SaveResponse
	(*ResurrectRequest)(nil),        // 26: pm0.v1.ResurrectRequest
	(*ResurrectResponse)(nil),       // 27: pm0.v1.ResurrectResponse
	(*UpdateDaemonRequest)(nil),     // 28: pm0.v1.UpdateDaemonRequest
	(*UpdateDaemonEvent)(nil),       // 29: pm0.v1.UpdateDaemonEvent
	(*KillDaemonRequest)(nil),       // 30: pm0.v1.KillDaemonRequest
	(*KillDaemonResponse)(nil),      // 31: pm0.v1.KillDaemonResponse
	(*Monit)(nil),                   // 32: pm0.v1.Monit
	(*ProcessEnv)(nil),              // 33: pm0.v1.ProcessEnv
	(*ProcessInfo)(nil),             // 34: pm0.v1.ProcessInfo
	nil,                             // 35: pm0.v1.ProcessSpec.EnvEntry
	nil,                             // 36: pm0.v1.ProcessEnv.EnvEntry
}
var file_daemon_proto_depIdxs = []int32{
	35, // 0: pm0.v1.ProcessSpec.env:type_name -> pm0.v1.ProcessSpec.EnvEntry
	5,  // 1: pm0.v1.StartProcessRequest.specs:type_name -> pm0.v1.ProcessSpec
	34, // 2: pm0.v1.StartProcessResponse.processes:type_name -> pm0.v1.ProcessInfo
	2,  // 3: pm0.v1.StopProcessRequest.selector:type_name -> pm0.v1.Selector
	2,  // 4: pm0.v1.RestartProcessRequest.selector:type_name -> pm0.v1.Selector
	5,  // 5: pm0.v1.RestartProcessRequest.updated_spec:type_name -> pm0.v1.ProcessSpec
	2,  // 6: pm0.v1.DeleteProcessRequest.selector:type_name -> pm0.v1.Selector
	2,  // 7: pm0.v1.ReloadProcessRequest.selector:type_name -> pm0.v1.Selector
	34, // 8: pm0.v1.ListProcessesResponse.processes:type_name -> pm0.v1.ProcessInfo
	2,  // 9: pm0.v1.DescribeProcessRequest.selector:type_name -> pm0.v1.Selector
	34, // 10: pm0.v1.DescribeProcessResponse.process:type_name -> pm0.v1.ProcessInfo
	2,  // 11: pm0.v1.StreamLogsRequest.selector:type_name -> pm0.v1.Selector
	1,  // 12: pm0.v1.LogLine.stream:type_name -> pm0.v1.LogLine.Stream
	36, // 13: pm0.v1.ProcessEnv.env:type_name -> pm0.v1.ProcessEnv.EnvEntry
	0,  // 14: pm0.v1.ProcessInfo.status:type_name -> pm0.v1.ProcessStatus
	32, // 15: pm0.v1.ProcessInfo.monit:type_name -> pm0.v1.Monit
	33, // 16: pm0.v1.ProcessInfo.pm2_env:type_name -> pm0.v1.ProcessEnv
	3,  // 17: pm0.v1.Daemon.Ping:input_type -> pm0.v1.PingRequest
	6,  // 18: pm0.v1.Daemon.StartProcess:input_type -> pm0.v1.StartProcessRequest
	8,  // 19: pm0.v1.Daemon.StopProcess:input_type -> pm0.v1.StopProcessRequest
	10, // 20: pm0.v1.Daemon.RestartProcess:input_type -> pm0.v1.RestartProcessRequest
	12, // 21: pm0.v1.Daemon.DeleteProcess:input_type -> pm0.v1.DeleteProcessRequest
	14, // 22: pm0.v1.Daemon.ReloadProcess:input_type -> pm0.v1.ReloadProcessRequest
	16, // 23: pm0.v1.Daemon.ScaleProcess:input_type -> pm0.v1.ScaleProcessRequest
	18, // 24: pm0.v1.Daemon.ListProcesses:input_type -> pm0.v1.ListProcessesRequest
	20, // 25: pm0.v1.Daemon.DescribeProcess:input_type -> pm0.v1.DescribeProcessRequest
	22, // 26: pm0.v1.Daemon.StreamLogs:input_type -> pm0.v1.StreamLogsRequest
	24, // 27: pm0.v1.Daemon.Save:input_type -> pm0.v1.SaveRequest
	26, // 28: pm0.v1.Daemon.Resurrect:input_type -> pm0.v1.ResurrectRequest
	28, // 29: pm0.v1.Daemon.UpdateDaemon:input_type -> pm0.v1.UpdateDaemonRequest
	30, // 30: pm0.v1.Daemon.KillDaemon:input_type -> pm0.v1.KillDaemonRequest
	4,  // 31: pm0.v1.Daemon.Ping:output_type -> pm0.v1.PingResponse
	7,  // 32: pm0.v1.Daemon.StartProcess:output_type -> pm0.v1.StartProcessResponse
	9,  // 33: pm0.v1.Daemon.StopProcess:output_type -> pm0.v1.StopProcessResponse
	11, // 34: pm0.v1.Daemon.RestartProcess:output_type -> pm0.v1.RestartProcessResponse
	13, // 35: pm0.v1.Daemon.DeleteProcess:output_type -> pm0.v1.DeleteProcessResponse
	15, // 36: pm0.v1.Daemon.ReloadProcess:output_type -> pm0.v1.ReloadProcessResponse
	17, // 37: pm0.v1.Daemon.ScaleProcess:output_type -> pm0.v1.ScaleProcessResponse
	19, // 38: pm0.v1.Daemon.ListProcesses:output_type -> pm0.v1.ListProcessesResponse
	21, // 39: pm0.v1.Daemon.DescribeProcess:output_type -> pm0.v1.DescribeProcessResponse
	23, // 40: pm0.v1.Daemon.StreamLogs:output_type -> pm0.v1.LogLine
	25, // 41: pm0.v1.Daemon.Save:output_type -> pm0.v1.SaveResponse
	27, // 42: pm0.v1.Daemon.Resurrect:output_type -> pm0.v1.ResurrectResponse
	29, // 43: pm0.v1.Daemon.UpdateDaemon:output_type -> pm0.v1.UpdateDaemonEvent
	31, // 44: pm0.v1.Daemon.KillDaemon:output_type -> pm0.v1.KillDaemonResponse
	31, // [31:45] is the sub-list for method output_type
	17, // [17:31] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		EnumInfos:         file_daemon_proto_enumTypes,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
