// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"benchmarks.mdx": () => import("../content/docs/benchmarks.mdx?collection=docs"), "cli/delete.mdx": () => import("../content/docs/cli/delete.mdx?collection=docs"), "cli/describe.mdx": () => import("../content/docs/cli/describe.mdx?collection=docs"), "cli/jlist.mdx": () => import("../content/docs/cli/jlist.mdx?collection=docs"), "cli/kill.mdx": () => import("../content/docs/cli/kill.mdx?collection=docs"), "cli/logs.mdx": () => import("../content/docs/cli/logs.mdx?collection=docs"), "cli/ping.mdx": () => import("../content/docs/cli/ping.mdx?collection=docs"), "cli/reload.mdx": () => import("../content/docs/cli/reload.mdx?collection=docs"), "cli/restart.mdx": () => import("../content/docs/cli/restart.mdx?collection=docs"), "cli/resurrect.mdx": () => import("../content/docs/cli/resurrect.mdx?collection=docs"), "cli/save.mdx": () => import("../content/docs/cli/save.mdx?collection=docs"), "cli/scale.mdx": () => import("../content/docs/cli/scale.mdx?collection=docs"), "cli/start.mdx": () => import("../content/docs/cli/start.mdx?collection=docs"), "cli/startup.mdx": () => import("../content/docs/cli/startup.mdx?collection=docs"), "cli/status.mdx": () => import("../content/docs/cli/status.mdx?collection=docs"), "cli/stop.mdx": () => import("../content/docs/cli/stop.mdx?collection=docs"), "cli/unstartup.mdx": () => import("../content/docs/cli/unstartup.mdx?collection=docs"), "core-concepts.mdx": () => import("../content/docs/core-concepts.mdx?collection=docs"), "ecosystem-file.mdx": () => import("../content/docs/ecosystem-file.mdx?collection=docs"), "faq.mdx": () => import("../content/docs/faq.mdx?collection=docs"), "guides/cicd.mdx": () => import("../content/docs/guides/cicd.mdx?collection=docs"), "guides/docker.mdx": () => import("../content/docs/guides/docker.mdx?collection=docs"), "guides/systemd.mdx": () => import("../content/docs/guides/systemd.mdx?collection=docs"), "guides/zero-downtime-deploys.mdx": () => import("../content/docs/guides/zero-downtime-deploys.mdx?collection=docs"), "http-api.mdx": () => import("../content/docs/http-api.mdx?collection=docs"), "installation.mdx": () => import("../content/docs/installation.mdx?collection=docs"), "introduction.mdx": () => import("../content/docs/introduction.mdx?collection=docs"), "migrating-from-pm2.mdx": () => import("../content/docs/migrating-from-pm2.mdx?collection=docs"), "quickstart.mdx": () => import("../content/docs/quickstart.mdx?collection=docs"), "troubleshooting.mdx": () => import("../content/docs/troubleshooting.mdx?collection=docs"), }),
};
export default browserCollections;